import type { FullReviewOutput } from "./index";

export function formatReview(result: FullReviewOutput): string {
  const { pr, lint, security } = result;

  // Header
  const lines: string[] = [
    `## 🤖 Automated PR Review`,
    ``,
    `### 📋 PR Summary`,
    `**${pr.title}** by @${pr.author}`,
    pr.body !== "(no description)" ? `> ${pr.body.split("\n")[0]}` : "",
    ``,
  ];

  // Files changed
  lines.push(`### 📁 Files Changed (${pr.files.length})`);
  for (const file of pr.files) {
    const icon =
      file.status === "added" ? "🟢" :
      file.status === "removed" ? "🔴" : "🟡";
    lines.push(
      `- ${icon} \`${file.filename}\` — +${file.additions} / -${file.deletions}`
    );
  }
  lines.push(``);

  // Lint results
  lines.push(`### 🔍 Lint Results`);
  if (lint.issues.length === 0) {
    lines.push(`✅ No lint issues found.`);
  } else {
    lines.push(`${lint.errorCount > 0 ? "❌" : "⚠️"} ${lint.errorCount} error(s), ${lint.warningCount} warning(s)`);
    lines.push(``);
    lines.push(`| Severity | File | Line | Rule | Message |`);
    lines.push(`|----------|------|------|------|---------|`);
    for (const issue of lint.issues.slice(0, 20)) {
      const icon = issue.severity === "error" ? "❌" : "⚠️";
      lines.push(
        `| ${icon} ${issue.severity} | \`${issue.filename}\` | ${issue.line}:${issue.column} | \`${issue.rule}\` | ${issue.message} |`
      );
    }
    if (lint.issues.length > 20) {
      lines.push(`\n_...and ${lint.issues.length - 20} more issues_`);
    }
  }
  lines.push(``);

  // Security results
  lines.push(`### 🔒 Security Scan`);
  if (security.flags.length === 0) {
    lines.push(`✅ No security issues detected.`);
  } else {
    const highFlags = security.flags.filter((f) => f.severity === "high");
    const medFlags  = security.flags.filter((f) => f.severity === "medium");
    lines.push(`${highFlags.length > 0 ? "🚨" : "⚠️"} ${security.flags.length} flag(s) found`);
    lines.push(``);
    lines.push(`| Severity | File | Line | Type | Detail |`);
    lines.push(`|----------|------|------|------|--------|`);
    for (const flag of security.flags) {
      const icon =
        flag.severity === "high" ? "🚨" :
        flag.severity === "medium" ? "⚠️" : "ℹ️";
      lines.push(
        `| ${icon} ${flag.severity} | \`${flag.filename}\` | ${flag.line} | ${flag.type} | ${flag.detail} |`
      );
    }
  }
  lines.push(``);

  // Recommendation
  const hasErrors    = lint.errorCount > 0;
  const hasHighSec   = security.flags.some((f) => f.severity === "high");
  const hasMedSec    = security.flags.some((f) => f.severity === "medium");
  const hasWarnings  = lint.warningCount > 0;

  lines.push(`### ✅ Recommendation`);
  if (hasErrors || hasHighSec) {
    lines.push(`**🔴 REQUEST CHANGES** — ${hasHighSec ? "High-severity security issues must be resolved before merging. " : ""}${hasErrors ? "Lint errors must be fixed." : ""}`);
  } else if (hasMedSec || hasWarnings) {
    lines.push(`**🟡 NEEDS DISCUSSION** — No blocking issues, but warnings and medium-severity findings are worth addressing.`);
  } else {
    lines.push(`**🟢 APPROVE** — No lint errors or security issues found. Looks good to merge.`);
  }

  lines.push(``);
  lines.push(`---`);
  lines.push(`_Review generated by pr-review-agent · ${new Date().toUTCString()}_`);

  return lines.filter((l) => l !== undefined).join("\n");
}
